{"name": "test_first_scenario", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 40\n +  where 40 = get_data()", "trace": "def test_first_scenario():\n        a=5\n        b=6\n>       assert a==get_data()\nE       assert 5 == 40\nE        +  where 40 = get_data()\n\ntest_allure_report.py:6: AssertionError"}, "start": 1716028441924, "stop": 1716028441924, "uuid": "84c145d0-9ad5-497a-9f10-e3955abf58ff", "historyId": "4721117b209e0679658ac3ca10d52268", "testCaseId": "4721117b209e0679658ac3ca10d52268", "fullName": "test_allure_report#test_first_scenario", "labels": [{"name": "suite", "value": "test_allure_report"}, {"name": "host", "value": "LAPTOP-3SVJ89ED"}, {"name": "thread", "value": "5852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_report"}]}